"""Importa para o banco (questions.json) o lote piloto de questões reais da Cesgranrio.

Fonte: BNDES, Seleção Pública Edital nº 01/2024 (Fundação Cesgranrio), provas objetivas da manhã
aplicadas em 13/10/2024, cargo Analista (nível superior). Cadernos e "Gabarito Final, após
avaliação dos recursos" baixados da página oficial do BNDES (Concursos, Seleção Pública 2024),
em 07/10/2026. A correspondência coluna do gabarito x caderno foi conferida pelo rodapé de cada
caderno (Prova 2 = Cibersegurança, Prova 3 = Desenvolvimento, Prova 7 = Ciências Contábeis,
Prova 10 = Direito); as questões 1 a 35 (Conhecimentos Básicos) são comuns a todos os perfis.

Critério de seleção (decisão de Yuri, 07/10/2026): só disciplinas equivalentes às da SEFAZ-BA
(Português, Estatística, Matemática Financeira, Economia e Finanças Públicas, Contabilidade,
Direito Tributário, Constitucional e Administrativo, TI). Ficam de fora as questões específicas
do BNDES ou de outras carreiras (atuação do BNDES, direito societário e bancário, processo civil),
as anuladas e as que dependem de figura.

Uso: python importar_cesgranrio_bndes2024.py   (idempotente: substitui o lote se já existir)
"""
import json
import os
import shutil
from datetime import date

BASE = os.path.dirname(os.path.abspath(__file__))
ARQ = os.path.join(BASE, "questions.json")
PREFIXO = "cesg_bndes2024_"

URL_PAGINA = "https://www.bndes.gov.br/wps/portal/site/home/quem-somos/trabalhar-no-bndes/concursos-selecao-publica-2024"
PROVAS = {
    "basicos": "Conhecimentos Básicos (comuns a todos os perfis de Analista)",
    "ciber": "Analista / Análise de Sistemas - Cibersegurança (Prova 2)",
    "desenv": "Analista / Análise de Sistemas - Desenvolvimento (Prova 3)",
    "contabeis": "Analista / Ciências Contábeis (Prova 7)",
    "direito": "Analista / Direito (Prova 10)",
}

# Perfis de cargo e escopo seguem o padrão já usado no banco para o mesmo assunto
TI = dict(category="ti", cargos=["auditor_ti"], escopo="edital_ba_2022")
GERAL_AMBOS = dict(category="general", cargos=["auditor_ti", "agente"], escopo="edital_ba_2022")
GERAL_AUDITOR = dict(category="general", cargos=["auditor_ti"], escopo="correlato")
GERAL_AMBOS_CORRELATO = dict(category="general", cargos=["auditor_ti", "agente"], escopo="correlato")


def q(prova, numero, perfil, subject, topic, question, options, correct, explanation, option_explanations, fundamento):
    item = {
        "id": f"{PREFIXO}{prova}_{numero}",
        "subject": subject,
        "topic": topic,
        "source": f"Cesgranrio - BNDES (2024) - {PROVAS[prova]}, questão {numero}",
        "question": question,
        "options": options,
        "correct": correct,
        "explanation": explanation,
        "option_explanations": option_explanations,
        "fundamento": fundamento,
        "banca": "CESGRANRIO",
        "certame": "BNDES 2024",
        "nivel": "superior",
        "gabarito_oficial_conferido": True,
        "gabarito_status": "definitivo",
        "origem": URL_PAGINA,
    }
    item.update(perfil)
    return item


QUESTOES = [
    # ------------------------------------------------------------------ Conhecimentos Básicos
    q("basicos", 6, GERAL_AUDITOR, "Economia do Setor Público", "Instrumentos de política fiscal",
      "Para o exercício de suas funções, o governo dispõe de um conjunto complexo de políticas: política fiscal, política monetária, política externa, política industrial, política de renda, dentre outras.\n\nSão instrumentos da política fiscal:",
      {"A": "controle sobre a taxa de câmbio e incentivo à exportação de bens e serviços",
       "B": "incentivos financeiros e incentivos creditícios para o setor de agropecuária",
       "C": "alterações salariais e geração de empregos",
       "D": "controle sobre as taxas de juros e controle sobre mecanismos de crédito",
       "E": "alterações nos gastos governamentais e incentivos fiscais"},
      "E",
      "Política fiscal é a atuação do governo sobre as receitas (tributação) e as despesas públicas. Alterar o gasto governamental e conceder incentivos fiscais são, portanto, os seus instrumentos típicos. Câmbio, juros e crédito pertencem às políticas cambial e monetária; salários e emprego, à política de rendas.",
      {"A": "Taxa de câmbio e estímulo à exportação são instrumentos da política cambial e comercial, não da fiscal.",
       "B": "Incentivos creditícios setoriais aproximam-se da política de crédito e da política agrícola; a alternativa não descreve os dois instrumentos gerais da política fiscal, que são o gasto público e a tributação.",
       "C": "Alterações salariais e geração de empregos dizem respeito à política de rendas e ao mercado de trabalho, não ao manejo de receitas e despesas públicas.",
       "D": "Controle de juros e de mecanismos de crédito é a essência da política monetária, conduzida pelo Banco Central.",
       "E": "Correta. Gastos governamentais (lado da despesa) e incentivos fiscais (lado da receita) são os instrumentos clássicos da política fiscal."},
      "Conceito de política fiscal: gestão de receitas e despesas públicas"),

    q("basicos", 8, GERAL_AUDITOR, "Finanças Públicas", "Subsídios: benefícios tributários, financeiros e creditícios",
      "Segundo o Tribunal de Contas da União, subsídio é transferência condicional de fundos pelo governo, em benefício de outra parte, com a finalidade de influenciar o comportamento dessa parte, para alcançar algum nível de atividade ou provisão. Há disposições preferenciais da legislação que concedem subsídios ou subvenções na forma de desembolsos efetivos realizados por meio das equalizações de juros e preços e da assunção das dívidas decorrentes de saldos de obrigações de responsabilidade do ente da Federação, cujos valores constam do orçamento.\n\nOs subsídios concedidos por meio de tais disposições são denominados",
      {"A": "benefícios tributários",
       "B": "benefícios creditícios",
       "C": "benefícios financeiros",
       "D": "desonerações tributárias",
       "E": "renúncia de receita tributária"},
      "C",
      "Na classificação de subsídios da União usada pelo TCU, benefícios financeiros são desembolsos efetivos, feitos por equalização de juros e preços e por assunção de dívidas, e por isso constam do orçamento. Benefícios creditícios são o custo implícito de programas oficiais de crédito com taxas subsidiadas; benefícios tributários são renúncias de receita.",
      {"A": "Benefícios tributários (gastos tributários) são renúncias de receita, e não desembolsos efetivos registrados como despesa no orçamento.",
       "B": "Benefícios creditícios correspondem ao custo implícito de empréstimos oficiais a taxas inferiores ao custo de captação; não se materializam em desembolsos de equalização ou de assunção de dívidas.",
       "C": "Correta. Desembolsos efetivos por equalização de juros e preços e por assunção de dívidas, com valores no orçamento, definem os benefícios financeiros.",
       "D": "Desoneração tributária reduz a arrecadação; é espécie de benefício tributário, sem desembolso.",
       "E": "Renúncia de receita (LRF, art. 14) é o oposto de desembolso: o Estado deixa de arrecadar, em vez de pagar."},
      "Classificação dos subsídios da União (TCU): benefícios tributários, financeiros e creditícios; LRF, art. 14"),

    q("basicos", 15, GERAL_AMBOS, "Estatística", "Coeficiente de variação",
      "Uma pesquisa coletou as seguintes informações sobre as variáveis salário e hora extra:\n\nVariável: média; desvio padrão\nSalário: 500; 50\nHora extra: 100; 20\n\nConsiderando-se essas informações, no que diz respeito à variação das variáveis salário e hora extra, conclui-se que:",
      {"A": "a variável salário variou mais.",
       "B": "a variável hora extra variou mais.",
       "C": "a variação comparativa dessas variáveis pode ser medida pelo desvio padrão.",
       "D": "as variáveis tiveram a mesma variação.",
       "E": "não é possível saber qual das variáveis sofreu maior variação."},
      "B",
      "Variáveis com médias diferentes são comparadas pela dispersão relativa, o coeficiente de variação (CV = desvio padrão / média). Salário: 50 / 500 = 10%. Hora extra: 20 / 100 = 20%. A hora extra variou mais.",
      {"A": "O salário tem desvio padrão absoluto maior (50), mas dispersão relativa menor: CV de 10% contra 20% da hora extra.",
       "B": "Correta. CV da hora extra = 20 / 100 = 20%, o dobro do CV do salário (50 / 500 = 10%).",
       "C": "O desvio padrão é medida absoluta, na unidade da variável; com médias tão diferentes, a comparação exige uma medida relativa, como o CV.",
       "D": "Os CV são diferentes (10% e 20%), logo as variações não são iguais.",
       "E": "Média e desvio padrão bastam para calcular o CV de cada variável e compará-las."},
      "Coeficiente de variação: CV = desvio padrão / média"),

    q("basicos", 16, GERAL_AMBOS, "Estatística", "Classificação de variáveis",
      "O uso de dados quantitativos e qualitativos é fundamental para a compreensão e a análise da situação de um país, servindo de importante subsídio à tomada de decisões. Esses dados são mensurados a partir de diferentes variáveis.\n\nSobre essas variáveis, verifica-se que",
      {"A": "estado civil, grau de instrução, região e salários são variáveis qualitativas.",
       "B": "salários, idade, grau de instrução e estado civil são variáveis quantitativas.",
       "C": "número de filhos é uma variável quantitativa discreta.",
       "D": "grau de instrução é uma variável qualitativa nominal.",
       "E": "região é uma variável quantitativa discreta."},
      "C",
      "Número de filhos resulta de contagem e só assume valores inteiros: é quantitativa discreta. Estado civil e região são qualitativas nominais; grau de instrução é qualitativa ordinal (tem ordem natural); salário e idade são quantitativas.",
      {"A": "Salário é variável quantitativa (contínua), e não qualitativa.",
       "B": "Grau de instrução e estado civil são categorias, isto é, variáveis qualitativas.",
       "C": "Correta. Número de filhos vem de contagem e assume valores inteiros (0, 1, 2...): quantitativa discreta.",
       "D": "Grau de instrução tem ordem natural entre as categorias (fundamental, médio, superior): é qualitativa ordinal, não nominal.",
       "E": "Região é categoria sem medida numérica: qualitativa nominal."},
      "Classificação de variáveis estatísticas: qualitativas (nominais e ordinais) e quantitativas (discretas e contínuas)"),

    q("basicos", 19, TI, "Business Intelligence e Big Data", "CRISP-DM: fase de compreensão dos dados",
      "O CRISP-DM (Cross-Industry Standard Process for Data Mining) é uma metodologia amplamente utilizada para a análise e mineração de dados. Ela fornece um framework estruturado para realizar projetos de análise de dados, cobrindo desde a compreensão inicial do problema até a implementação das soluções. O ciclo CRISP-DM é composto por seis etapas principais: (i) Compreensão do negócio; (ii) Compreensão dos dados; (iii) Preparação dos dados; (iv) Modelagem; (v) Avaliação; (vi) Desenvolvimento.\n\nNa fase de compreensão dos dados, as tarefas desempenhadas são:",
      {"A": "limpeza dos dados, tratando dados faltantes, corrigindo erros e removendo outliers.",
       "B": "transformação e integração dos dados, com normalização, agregação e criação de novas variáveis.",
       "C": "análise e entendimento das características dos dados e de como eles se relacionam com os objetivos do negócio.",
       "D": "seleção de técnicas de modelagem apropriadas (regressão, classificação, clustering e outras).",
       "E": "ajuste dos parâmetros dos modelos e validação dos resultados."},
      "C",
      "No CRISP-DM, a compreensão dos dados reúne coleta inicial, descrição, exploração e verificação da qualidade dos dados, sempre à luz dos objetivos do negócio. Limpeza, transformação e integração são da preparação; escolha de técnicas e ajuste de parâmetros são da modelagem; validação de resultados é da avaliação.",
      {"A": "Limpeza (dados faltantes, erros, outliers) é tarefa da fase de preparação dos dados.",
       "B": "Transformação, integração, normalização e criação de variáveis também pertencem à preparação dos dados.",
       "C": "Correta. Explorar e entender as características dos dados e sua relação com os objetivos do negócio é o núcleo da compreensão dos dados.",
       "D": "Escolher técnicas de modelagem é a primeira tarefa da fase de modelagem.",
       "E": "Ajuste de parâmetros é da modelagem, e a validação dos resultados ocorre na avaliação."},
      "CRISP-DM 1.0 (Chapman et al., 2000): fases e tarefas"),

    q("basicos", 25, GERAL_AMBOS, "Língua Portuguesa", "Pontuação: emprego da vírgula",
      "Com relação à exigência do uso das vírgulas, considerando-se as regras de pontuação vigentes, respeita-se a norma-padrão da língua portuguesa em:",
      {"A": "A cultura do consumismo que se enraíza na sociedade moderna, faz com que indivíduos, influenciados por propagandas, redes sociais e pela pressão do grupo priorizem a aquisição de bens materiais em detrimento de experiências.",
       "B": "As práticas consumistas e as estratégias de marketing cada vez mais sofisticadas, fazem com que a obsolescência programada se torne uma norma, forçando os consumidores a substituir seus produtos com frequência, o que gera mais lixo e impacto ambiental.",
       "C": "Com o aumento do poder aquisitivo em diversas partes do mundo, o consumismo torna-se uma ferramenta para suprir carências emocionais, levando as pessoas a acreditarem que a felicidade pode ser comprada, o que resulta em sentimentos constantes de frustração.",
       "D": "O consumismo desenfreado, impulsionado pela incessante busca por status leva as pessoas a adquirir produtos e serviços que muitas vezes não são necessários, o que alimenta a necessidade de um consumo ainda maior.",
       "E": "O consumismo, visto por muitos, como uma forma de expressão e identidade, acaba por condenar as pessoas a um ciclo interminável de compras, dívidas e trabalho, fazendo, assim, com que esqueçamos o verdadeiro sentido da vida."},
      "C",
      "Na frase correta, a vírgula isola o adjunto adverbial anteposto (\"Com o aumento do poder aquisitivo...\"), a oração reduzida de gerúndio (\"levando as pessoas...\") e o aposto resumitivo (\"o que resulta...\"). Nas demais, há vírgula entre sujeito e verbo ou intercalação aberta e não fechada.",
      {"A": "Há vírgula indevida entre o sujeito (\"A cultura do consumismo que se enraíza na sociedade moderna\") e o verbo \"faz\"; além disso, falta a vírgula que fecharia a intercalação após \"pressão do grupo\".",
       "B": "A vírgula depois de \"sofisticadas\" separa o sujeito composto do verbo \"fazem\", o que a norma-padrão não admite.",
       "C": "Correta. Vírgulas justificadas: adjunto adverbial deslocado para o início, oração reduzida de gerúndio e aposto oracional introduzido por \"o que\".",
       "D": "A intercalação \"impulsionado pela incessante busca por status\" foi aberta por vírgula e não foi fechada antes do verbo \"leva\".",
       "E": "A vírgula depois de \"visto por muitos\" separa o particípio de seu complemento (\"como uma forma de expressão\"); o correto é isolar a expressão inteira: \"O consumismo, visto por muitos como uma forma de expressão e identidade, acaba...\"."},
      "Gramática normativa: vedação de vírgula entre sujeito e verbo; isolamento de adjuntos adverbiais antepostos, orações reduzidas e apostos"),

    q("basicos", 26, GERAL_AMBOS, "Língua Portuguesa", "Concordância verbal",
      "Com relação à concordância verbal, considerando-se as regras vigentes, respeita-se a norma-padrão da língua portuguesa, no verbo destacado (em maiúsculas; no caderno original, em negrito), em:",
      {"A": "Futuramente, em nossa sociedade, HAVERÃO constantes pressões para que as pessoas consumam cada vez mais, já que o sucesso está diretamente ligado à posse de bens materiais.",
       "B": "Alimentada pelo desejo de status e reconhecimento social, a compulsão por compras, especialmente de itens de luxo, TÊM-se intensificado, levando muitas pessoas a endividarem-se em busca de uma felicidade ilusória.",
       "C": "A crescente influência da publicidade e o constante surgimento de novas tecnologias IMPULSIONOU o consumismo, fazendo com que as pessoas adquiram produtos desnecessários e acumulem dívidas.",
       "D": "FOMENTAM o consumismo, de maneira desenfreada, a constante inovação tecnológica e a incessante busca por status, o que também cria um ciclo vicioso de insatisfação e desperdício.",
       "E": "A necessidade de adquirir novos produtos, mesmo que desnecessários, estimulada por campanhas publicitárias e pelas redes sociais, ENRAIZARAM novas práticas de consumo na sociedade, o que criou um ciclo interminável de consumo e insatisfação."},
      "D",
      "Em \"Fomentam\", o sujeito é composto (\"a constante inovação tecnológica e a incessante busca por status\") e vem depois do verbo; o plural é sempre aceito nesse caso. Nas demais, o verbo não concorda com o núcleo do sujeito ou o verbo haver existencial foi flexionado.",
      {"A": "\"Haver\" no sentido de existir é impessoal e fica no singular: \"haverá constantes pressões\".",
       "B": "O núcleo do sujeito é \"compulsão\" (singular): \"tem-se intensificado\".",
       "C": "Sujeito composto anteposto ao verbo exige o plural: \"A crescente influência... e o constante surgimento... impulsionaram\".",
       "D": "Correta. Sujeito composto posposto (\"a constante inovação tecnológica e a incessante busca por status\") admite o plural, que é sempre correto.",
       "E": "O núcleo do sujeito é \"necessidade\" (singular): \"enraizou novas práticas\"."},
      "Gramática normativa: concordância com sujeito composto anteposto e posposto; impessoalidade do verbo haver existencial"),

    q("basicos", 29, GERAL_AMBOS, "Língua Portuguesa", "Coesão: função textual dos dois-pontos",
      "No segundo parágrafo, o trecho que se segue ao sinal de dois pontos em \"tais como: a exposição dos produtos em vitrines, a fixação e a exibição de preços em etiquetas, a criação de datas comemorativas e promocionais, a incorporação de feriados religiosos e cívicos ao calendário de compras e a transformação das visitas às lojas em momentos de entretenimento.\" exerce a função textual de\n\n(Contexto: o trecho exemplifica \"inovações no comércio da época que permanecem no nosso cotidiano presente\", impulsionadas pelas lojas de departamentos do século XIX, no texto \"O consumo como forma de expressão e de pertencimento\", de Danielle Kiffer.)",
      {"A": "adição",
       "B": "causalidade",
       "C": "consequência",
       "D": "contraposição",
       "E": "detalhamento"},
      "E",
      "Depois dos dois-pontos vem a enumeração que especifica quais são as inovações mencionadas antes; o trecho detalha, por exemplos, a ideia anterior.",
      {"A": "Os itens da enumeração somam-se entre si, mas a função do trecho como um todo, em relação ao que vem antes, é especificar as inovações.",
       "B": "O trecho não apresenta a causa das inovações; lista quais foram.",
       "C": "Não há relação de efeito: as práticas enumeradas são as próprias inovações, e não um resultado delas.",
       "D": "Não há oposição entre o trecho e a afirmação anterior; há continuidade e especificação.",
       "E": "Correta. Os dois-pontos introduzem uma enumeração que detalha e exemplifica \"inovações no comércio da época\"."},
      "Gramática normativa e coesão textual: dois-pontos como introdutor de enumeração explicativa"),

    # ------------------------------------------------------------------ Prova 2: Cibersegurança
    q("ciber", 36, TI, "Segurança da Informação", "Tipos de código malicioso",
      "As divisões categóricas dos códigos maliciosos, também conhecidos como malware, servem para homogeneizar os tipos de tratamento e resposta a essas ameaças.\n\nPara implementar um spyware em uma máquina-alvo, o tipo de malware mais indicado para ser usado na infecção é um(a)",
      {"A": "trojan, pois o usuário do sistema terá interesse em usá-lo e é silencioso.",
       "B": "vírus, pois são notórios pela capacidade de se replicar autonomamente em diversos computadores de uma rede.",
       "C": "worm, pois é capaz de se replicar em diversas áreas da memória (seja principal ou secundária) de um único dispositivo-alvo.",
       "D": "spear phishing, pois usa diversos computadores controlados para infectar um alvo específico.",
       "E": "botnet, pois engana o usuário e o leva a fornecer as suas credenciais a um programa conhecido como botmaster."},
      "A",
      "O cavalo de troia (trojan) se apresenta como programa útil e é executado pelo próprio usuário, instalando sem alarde cargas como spyware. Não precisa se replicar, o que o torna discreto, característica desejada para espionagem.",
      {"A": "Correta. O trojan é instalado pelo próprio usuário, atraído pela função aparente, e atua silenciosamente, ideal para implantar spyware.",
       "B": "Vírus dependem de um hospedeiro e da execução dele para se propagar; replicação autônoma pela rede descreve worm. Propagação ruidosa também não favorece a espionagem.",
       "C": "Worm se propaga sozinho entre dispositivos da rede, explorando vulnerabilidades; a definição dada (replicação em áreas de memória de um único dispositivo) está errada.",
       "D": "Spear phishing é engenharia social direcionada (mensagem personalizada), não um conjunto de computadores controlados; isso seria uma botnet.",
       "E": "Botnet é a rede de máquinas infectadas comandadas pelo botmaster; não é um golpe para obter credenciais do usuário."},
      "Cartilha de Segurança para Internet (CERT.br), fascículo Códigos Maliciosos"),

    q("ciber", 41, TI, "Segurança da Informação", "ISO/IEC 27001:2022 e o ciclo PDCA",
      "A Norma ISO/27001:2022 elenca as boas práticas na implantação de um sistema de gestão de segurança da informação (SGSI) para organizações. Essa norma é calcada na estrutura PDCA (Plan, Do, Check, Act) e elenca ações a serem feitas a cada uma das etapas.\n\nCom relação ao ciclo PDCA no contexto da implantação de um SGSI, a estrutura adotada é",
      {"A": "padronizada, com cada etapa sendo executada uma vez, e com maior relevância para a etapa de planejamento.",
       "B": "única para cada organização, devendo ter apenas etapas consideradas aplicáveis à organização onde está sendo implementada.",
       "C": "elíptica, com a etapa de atuação baseada nos resultados avaliados na etapa de execução.",
       "D": "iterativa, com uma etapa de planejamento ocorrendo após cada etapa de atuação.",
       "E": "quadrada, com cada etapa sendo executada uma vez, e de igual relevância para o sucesso."},
      "D",
      "O SGSI deve ser melhorado continuamente (cláusula 10 da ISO/IEC 27001:2022). No PDCA, isso significa um ciclo que se repete: cada etapa de agir (Act) alimenta um novo planejamento (Plan).",
      {"A": "O ciclo não é executado uma única vez; a melhoria contínua exige repetição.",
       "B": "Os requisitos das cláusulas 4 a 10 da norma são obrigatórios para quem declara conformidade; o que se ajusta à organização é a seleção de controles (Declaração de Aplicabilidade), não as etapas do ciclo.",
       "C": "\"Elíptica\" não descreve o modelo, e a etapa de agir se baseia nos resultados da verificação (Check), não da execução (Do).",
       "D": "Correta. O PDCA é iterativo: após agir, planeja-se de novo, o que materializa a melhoria contínua do SGSI.",
       "E": "Também supõe execução única de cada etapa, o que contraria a melhoria contínua."},
      "ABNT NBR ISO/IEC 27001:2022, cláusulas 1 e 10"),

    q("ciber", 43, TI, "Segurança da Informação", "ISO/IEC 27005:2023: definição de vulnerabilidade",
      "A ABNT NBR ISO/IEC 27005:2023 é uma norma com orientações para ajudar as organizações na realização de atividades de gestão de riscos de segurança da informação. Essa norma apresenta termos e definições importantes, com o propósito de facilitar a compreensão do documento da norma e de evitar ambiguidades que possam provocar uma interpretação errônea do seu texto.\n\nDe acordo com essa norma, vulnerabilidade é a(o)",
      {"A": "causa potencial de um incidente de segurança da informação que pode resultar em danos a um sistema ou prejuízos a uma organização.",
       "B": "fraqueza de um ativo ou controle que pode ser explorada e então pode ocorrer um evento com uma consequência negativa.",
       "C": "ocorrência ou mudança de um conjunto específico de circunstâncias.",
       "D": "elemento que, individualmente ou combinado, tem o potencial para dar origem ao risco.",
       "E": "evento de segurança da informação indesejado ou inesperado que tem probabilidade significativa de comprometer as operações do negócio."},
      "B",
      "Vulnerabilidade é a fraqueza (de um ativo ou de um controle) que uma ameaça pode explorar. As demais alternativas trazem as definições de ameaça, evento, fonte de risco e incidente.",
      {"A": "Causa potencial de um incidente é a definição de ameaça.",
       "B": "Correta. Vulnerabilidade é a fraqueza de um ativo ou controle que pode ser explorada, levando a um evento com consequência negativa.",
       "C": "Ocorrência ou mudança de um conjunto de circunstâncias é a definição de evento.",
       "D": "Elemento com potencial para dar origem ao risco é a definição de fonte de risco.",
       "E": "Evento indesejado ou inesperado com probabilidade significativa de comprometer as operações descreve um incidente de segurança da informação."},
      "ABNT NBR ISO/IEC 27005:2023, seção 3 (termos alinhados à ISO/IEC 27000 e à ISO 31000)"),

    q("ciber", 50, TI, "Segurança da Informação", "Ataques em rede local: ARP spoofing",
      "Um atacante presente numa rede local quer realizar um ataque para atuar como man-in-the-middle entre uma estação vítima e o default gateway da rede. Para executar esse ataque, o atacante quer fazer com que a estação da vítima associe o endereço MAC usado pelo atacante ao endereço IP do default gateway da rede. Além disso, quer fazer com que o default gateway da rede associe o endereço MAC usado pelo atacante ao endereço IP da estação da vítima.\n\nPara conseguir realizar essas associações, o atacante deve usar a técnica de",
      {"A": "IP Spoofing",
       "B": "ARP Spoofing",
       "C": "ICMP Spoofing",
       "D": "TCP Flooding",
       "E": "TCP Hijacking"},
      "B",
      "O ARP faz a associação entre endereço IP e endereço MAC na rede local. Enviando respostas ARP forjadas à vítima e ao gateway (envenenamento de cache ARP), o atacante faz os dois associarem o MAC dele aos IPs um do outro e passa a intermediar o tráfego.",
      {"A": "IP spoofing falsifica o endereço IP de origem dos pacotes; não altera a associação entre IP e MAC nas tabelas ARP.",
       "B": "Correta. Respostas ARP forjadas envenenam o cache ARP da vítima e do gateway, colocando o MAC do atacante no lugar dos legítimos.",
       "C": "Mensagens ICMP forjadas (como redirect) podem alterar rotas, mas não as associações IP-MAC.",
       "D": "TCP flooding (por exemplo, SYN flood) é ataque de negação de serviço, não de interceptação.",
       "E": "TCP hijacking é o sequestro de uma sessão TCP já estabelecida; não é a técnica que cria as associações IP-MAC falsas."},
      "RFC 826 (ARP); técnica de envenenamento de cache ARP"),

    q("ciber", 56, TI, "Segurança da Informação", "Serviços de segurança: irretratabilidade",
      "A fim de garantir a segurança da informação, é preciso adotar um conjunto de medidas de proteção para tornar sistemas de informação e sistemas de comunicação resistentes a ataques. Dentre essas medidas de proteção, existe uma que visa fornecer evidências que podem ser armazenadas e, posteriormente, apresentadas a terceiros, para resolver disputas que surgem se e quando uma comunicação é negada por uma das entidades envolvidas.\n\nEssa medida de proteção é conhecida como",
      {"A": "integridade",
       "B": "autenticidade",
       "C": "irretroatividade",
       "D": "irretratabilidade",
       "E": "confidencialidade"},
      "D",
      "Irretratabilidade (não repúdio) produz provas, como assinaturas digitais e registros, que impedem uma parte de negar ter enviado ou recebido uma comunicação e podem ser apresentadas a terceiros.",
      {"A": "Integridade garante que os dados não foram alterados indevidamente; não gera prova contra a negação de autoria.",
       "B": "Autenticidade confirma a identidade da origem, mas não produz, por si, evidência oponível a terceiros em uma disputa.",
       "C": "Irretroatividade não é serviço de segurança da informação; é princípio jurídico.",
       "D": "Correta. O não repúdio (irretratabilidade) fornece evidências armazenáveis para resolver disputas sobre comunicações negadas.",
       "E": "Confidencialidade protege o sigilo da informação, sem relação com prova de autoria."},
      "ITU-T X.800, serviço de não repúdio"),

    q("ciber", 59, TI, "Segurança da Informação", "Operações de segurança: SOAR",
      "As equipes do Security Operation Center (SOC) da organização, muitas vezes, são inundadas com tarefas repetitivas e demoradas que prejudicam e reduzem a eficiência na resposta aos incidentes. Para minimizar esse problema, um conjunto de tecnologias de segurança cibernética permite que as organizações respondam a alguns incidentes automaticamente, possibilitando que os administradores lidem com alertas de segurança, sem a necessidade de intervenção manual. Para isso, englobam três importantes recursos de software usados pelas equipes de cibersegurança: gerenciamento de casos e de fluxos de trabalho; automação de tarefas e acesso a meios centralizados de consulta; e compartilhamento de informações sobre ameaças.\n\nEsse conjunto de tecnologias de segurança cibernética é conhecido como",
      {"A": "IPS",
       "B": "DLP",
       "C": "WAF",
       "D": "CASB",
       "E": "SOAR"},
      "E",
      "SOAR (Security Orchestration, Automation and Response) combina orquestração, automação de respostas com playbooks e gestão de casos, integrando as ferramentas do SOC e informações sobre ameaças.",
      {"A": "IPS inspeciona o tráfego e bloqueia intrusões em tempo real; não faz gestão de casos nem orquestração da resposta.",
       "B": "DLP previne o vazamento de dados sensíveis.",
       "C": "WAF filtra o tráfego HTTP para proteger aplicações web.",
       "D": "CASB intermedeia o acesso a serviços de nuvem e aplica políticas de segurança sobre eles.",
       "E": "Correta. SOAR reúne gestão de casos e fluxos, automação de tarefas e compartilhamento de inteligência de ameaças para o SOC."},
      "Definição de SOAR (Security Orchestration, Automation and Response) usada pelo mercado de operações de segurança"),

    # ------------------------------------------------------------------ Prova 3: Desenvolvimento
    q("desenv", 40, TI, "Engenharia de Software", "Análise de Pontos de Função: Saída Externa",
      "Uma equipe de desenvolvimento está trabalhando em um sistema de gestão de pedidos, no qual é necessário implementar uma transação que gera um relatório detalhado de vendas. Esse relatório contém informações sobre as vendas do dia, agrupadas por categoria de produto, cliente e vendedor. O usuário pode selecionar a data específica como entrada para gerar o relatório. O relatório gerado não permite navegação ou consulta adicional e é produzido para ser impresso.\n\nDada a descrição da transação, qual tipo de ponto de função deve ser contado?",
      {"A": "Consulta Externa",
       "B": "Entrada Externa",
       "C": "Impressão Externa",
       "D": "Relatório Externo",
       "E": "Saída Externa"},
      "E",
      "Relatório com dados agrupados (consolidação por categoria, cliente e vendedor) envolve processamento que deriva dados, o que caracteriza a Saída Externa (SE) no IFPUG. A Consulta Externa só recupera dados, sem cálculo nem dado derivado.",
      {"A": "Consulta Externa apenas recupera e apresenta dados, sem cálculos nem dados derivados; o agrupamento por categoria, cliente e vendedor exige processamento adicional.",
       "B": "Entrada Externa processa dados vindos de fora da fronteira para manter arquivos lógicos internos; a data informada é só parâmetro de seleção.",
       "C": "\"Impressão Externa\" não existe como função transacional no IFPUG.",
       "D": "\"Relatório Externo\" também não é tipo de função do IFPUG.",
       "E": "Correta. A geração de dados derivados (consolidações) caracteriza a Saída Externa."},
      "IFPUG, Manual de Práticas de Contagem: funções transacionais (EE, CE e SE)"),

    q("desenv", 42, TI, "Segurança da Informação", "Autenticação multifator e RBAC",
      "Em uma aplicação financeira, um banco está implementando a autenticação multifatorial dos usuários junto com um sistema de Controle de Acesso Baseado em Papéis (RBAC, sigla em inglês) para gerenciar as permissões desses mesmos usuários.\n\nConsiderando-se esse contexto, quando implementado, o RBAC",
      {"A": "atribuirá permissões baseadas em funções sem considerar a identidade do usuário, enquanto a autenticação atribuirá permissões diretamente aos usuários.",
       "B": "lidará exclusivamente com a autenticação dos usuários, garantindo que apenas usuários autenticados possam acessar a aplicação.",
       "C": "será responsável por determinar as permissões dos usuários com base em seus papéis, enquanto a autenticação verificará a identidade dos usuários antes de atribuir esses papéis.",
       "D": "será independente da autenticação, e ambos não se relacionarão na gestão de acesso.",
       "E": "substituirá a necessidade de autenticação multifatorial, uma vez que os papéis já definem quem pode acessar a aplicação."},
      "C",
      "Autenticação (aqui, multifator) confirma quem é o usuário; autorização decide o que ele pode fazer. No RBAC, as permissões são ligadas a papéis, e o usuário autenticado recebe as permissões dos papéis que lhe foram atribuídos.",
      {"A": "O RBAC depende da identidade, pois é ela que está associada aos papéis; e a autenticação não atribui permissões.",
       "B": "RBAC é mecanismo de autorização, não de autenticação.",
       "C": "Correta. Autenticação verifica a identidade; o RBAC define as permissões a partir dos papéis do usuário.",
       "D": "As duas etapas são complementares e encadeadas: só se autoriza quem foi autenticado.",
       "E": "Papéis não comprovam identidade; sem autenticação forte, qualquer pessoa com a credencial assumiria os papéis do titular."},
      "Modelo RBAC do NIST (padrão ANSI/INCITS 359); distinção entre autenticação e autorização"),

    q("desenv", 51, TI, "Governança de TI", "Gestão financeira de TI: cálculo do ROI",
      "Uma empresa de TI investiu na compra de um novo software de Gestão de Infraestrutura que ao ser aplicado gerou uma receita anual suplementar de R$ 445.890,00. Em termos de custos desse investimento, houve aplicação de R$ 23.340,00 em marketing, de R$ 60.230,00 na compra de novas versões do sistema operacional, para todos os computadores da empresa, e de R$ 30.120,00 em treinamento. Observaram-se também, no período avaliado, gastos de R$ 10.080,00 em seleção de pessoal na área de segurança patrimonial e de R$ 23.670,00 na aquisição de material de expediente e consumo na área financeira, valores estes que foram lançados em rubrica de projetos já antigos da empresa.\n\nPara esse caso, o Retorno sobre o Investimento (ROI, sigla em inglês) no novo software de Gestão de Infraestrutura foi de",
      {"A": "101,20%",
       "B": "202,40%",
       "C": "228,90%",
       "D": "292,20%",
       "E": "457,80%"},
      "D",
      "ROI = (ganho - custo do investimento) / custo do investimento. Custos do projeto: 23.340 + 60.230 + 30.120 = 113.690. Os gastos com seleção de pessoal e material de expediente pertencem a projetos antigos e ficam de fora. ROI = (445.890 - 113.690) / 113.690 = 332.200 / 113.690 = 2,922, ou seja, 292,20%.",
      {"A": "Não corresponde à fórmula do ROI aplicada aos custos do projeto (resultado correto: 292,20%).",
       "B": "Resulta de incluir indevidamente os gastos de projetos antigos (10.080 + 23.670) no custo: (445.890 - 147.440) / 147.440 = 202,4%.",
       "C": "Não corresponde à fórmula do ROI aplicada aos custos do projeto (resultado correto: 292,20%).",
       "D": "Correta. (445.890 - 113.690) / 113.690 = 2,922 = 292,20%.",
       "E": "Não corresponde à fórmula do ROI aplicada aos custos do projeto (resultado correto: 292,20%)."},
      "ROI = (ganho - investimento) / investimento; só entram os custos atribuíveis ao projeto"),

    q("desenv", 52, TI, "Governança de TI - ITIL v4", "Métricas de mudança (CAB e RFC)",
      "Uma empresa está aplicando o ITIL em sua versão atual para trabalhar com seu desenvolvimento de serviços de TI. No momento, a empresa está definindo as métricas de mensuração para processos de transições de serviço. O foco atual é a medição do número de reuniões do Change Advisory Board (CAB) e o número de Requests for Change (RFC) aceitos x rejeitados.\n\nNesse caso, esses indicadores-chave de desempenho (KPI, sigla em inglês) do ITIL, usados para processos de transições de serviço, auxiliam na(o)",
      {"A": "gestão de ativos",
       "B": "gestão de mudança",
       "C": "gestão de capacidade de serviços",
       "D": "planejamento de suporte",
       "E": "validação de testes"},
      "B",
      "CAB (comitê consultivo de mudanças) e RFC (requisição de mudança) são elementos da gestão de mudanças, chamada no ITIL 4 de prática de habilitação de mudanças (change enablement). Reuniões do CAB e taxa de RFC aceitas ou rejeitadas medem esse processo.",
      {"A": "Gestão de ativos de TI acompanha inventário, custos e ciclo de vida dos ativos, não decisões sobre mudanças.",
       "B": "Correta. CAB e RFC pertencem à gestão (habilitação) de mudanças.",
       "C": "Gestão de capacidade e desempenho mede utilização e desempenho dos serviços.",
       "D": "Planejamento de suporte não usa CAB nem RFC como indicadores.",
       "E": "Validação e teste de serviço mede cobertura de testes e defeitos, não o fluxo de requisições de mudança."},
      "ITIL 4, prática de habilitação de mudanças (change enablement)"),

    q("desenv", 69, TI, "Banco de Dados", "Níveis de isolamento: SERIALIZABLE",
      "No contexto de um Sistema Gerenciador de Banco de Dados (SGBD), é possível definir o nível de isolamento de uma transação por meio do comando SET TRANSACTION ISOLATION LEVEL. Há vários níveis de isolamento possíveis.\n\nEntre tais níveis encontra-se o SERIALIZABLE, que",
      {"A": "configura o SGBD para modo de leitura de todas as suas tabelas.",
       "B": "define que apenas uma transação será executada por vez pelo SGBD.",
       "C": "garante o mais alto nível possível de isolamento de uma transação.",
       "D": "permite a serialização de objetos JSON em uma transação.",
       "E": "prepara uma transação W para enviar dados a outra transação Y."},
      "C",
      "SERIALIZABLE é o nível mais alto do padrão SQL: o resultado da execução concorrente deve ser equivalente a alguma execução serial, o que impede leitura suja, leitura não repetível e leitura fantasma.",
      {"A": "Não torna as tabelas somente leitura; transações serializáveis podem gravar normalmente.",
       "B": "O SGBD continua executando transações de forma concorrente; exige-se apenas que o resultado seja equivalente a uma ordem serial.",
       "C": "Correta. É o nível de isolamento mais restritivo previsto no padrão SQL.",
       "D": "Não tem relação com serialização de objetos JSON; o nome vem da equivalência a uma execução serial.",
       "E": "Níveis de isolamento não servem para uma transação enviar dados a outra."},
      "ISO/IEC 9075 (SQL): níveis de isolamento de transações"),

    # ------------------------------------------------------------------ Prova 7: Ciências Contábeis
    q("contabeis", 36, GERAL_AMBOS, "Contabilidade Geral", "Ebitda (Lajida) a partir da DRE e da DFC",
      "Uma empresa S.A. do ramo de shopping centers apresentou as seguintes informações: Demonstração do Resultado do Exercício, Nota Explicativa e extrato da Demonstração dos Fluxos de Caixa. A empresa reconhece seus shopping centers como propriedades para investimentos e as avalia pelo método do custo.\n\nDemonstração do Resultado do Exercício (20X4)\nReceita operacional líquida: 2.000.000\nCusto dos serviços prestados: 300.000\nLucro Bruto: 1.700.000\nReceitas (despesas) operacionais\nDespesas administrativas - Sede: 120.000\nDespesas administrativas - Propriedades: 80.000\nResultado de Equivalência Patrimonial: 50.000\nDepreciações e amortizações: 30.000\nLucro operacional antes do resultado financeiro: 1.420.000\nDespesa financeira: 150.000\nReceita financeira: 70.000\nLucro antes dos impostos: 1.340.000\nImpostos: 150.000\nLucro Líquido: 1.190.000\n\nNota explicativa - Abertura dos custos por natureza\nDurante o exercício findo, em 31 de dezembro de 20X4, a empresa incorreu em custos decorrentes da participação nos condomínios civis dos shoppings em operação e em custos de depreciação das propriedades para investimentos.\n\nDemonstração dos Fluxos de Caixa (extrato, 20X4)\nFluxo de caixa de atividades operacionais\nLucro líquido: 1.190.000\nAjustes:\nDepreciações e amortizações: 220.000\nEquivalência Patrimonial: 50.000\nPerdas estimadas para crédito de liquidação duvidosa: 60.000\nContas a receber não faturadas: 30.000\n\nConsiderando-se as informações apresentadas, identificou-se um Ebitda, em reais, de:",
      {"A": "1.710.000",
       "B": "1.640.000",
       "C": "1.520.000",
       "D": "1.500.000",
       "E": "1.450.000"},
      "B",
      "Ebitda (Lajida, Resolução CVM 156/2022) = lucro líquido + tributos sobre o lucro + resultado financeiro líquido + depreciação e amortização. A depreciação total é a da DFC (220.000), pois parte dela está no custo dos serviços (depreciação das propriedades, conforme a nota). Ebitda = 1.190.000 + 150.000 + (150.000 - 70.000) + 220.000 = 1.640.000. A equivalência patrimonial não é excluída no Ebitda da CVM.",
      {"A": "Soma a receita financeira em vez de deduzi-la: 1.190.000 + 150.000 + 150.000 + 220.000 = 1.710.000.",
       "B": "Correta. 1.190.000 + 150.000 + 80.000 (resultado financeiro líquido) + 220.000 = 1.640.000.",
       "C": "Não incorpora corretamente a depreciação total de 220.000 informada na DFC.",
       "D": "Usa só a depreciação da DRE (30.000) e ainda exclui a equivalência: 1.420.000 + 30.000 + 50.000 = 1.500.000; ignora a depreciação embutida no custo.",
       "E": "Soma ao lucro operacional apenas a depreciação da DRE (1.420.000 + 30.000), ignorando a depreciação incluída no custo dos serviços."},
      "Resolução CVM nº 156/2022 (Lajida/Ebitda); CPC 03 (R2), DFC pelo método indireto"),

    q("contabeis", 44, GERAL_AMBOS_CORRELATO, "Matemática Financeira", "Juros compostos: saldo devedor e parcela final",
      "Uma empresa contraiu um empréstimo no valor de 400 mil reais, em agosto de 2024. Após exatamente 1 mês, em setembro de 2024, pagou 150 mil reais. Em outubro de 2024, após exatos dois meses da data do empréstimo, efetuou um pagamento de 170 mil reais. E em novembro de 2024, após exatos 3 meses da data do empréstimo, quitou a dívida, pagando a última parcela. Sabe-se que a taxa de juros compostos desse empréstimo foi de 2% ao mês.\n\nAssim, para a quitação do empréstimo, o valor da última parcela paga em novembro de 2024, em milhares de reais, foi de, aproximadamente,",
      {"A": "95,0",
       "B": "98,5",
       "C": "104,5",
       "D": "112,3",
       "E": "114,6"},
      "A",
      "Capitalizando o saldo mês a mês a 2%: setembro, 400 x 1,02 = 408,0, menos 150 = 258,0; outubro, 258,0 x 1,02 = 263,16, menos 170 = 93,16; novembro, 93,16 x 1,02 = 95,02. A última parcela é de cerca de 95,0 mil.",
      {"A": "Correta. Saldo em novembro: 93,16 x 1,02 = 95,02 mil.",
       "B": "Não confere com o saldo devedor capitalizado a 2% ao mês (95,02 mil).",
       "C": "Não confere com o saldo devedor capitalizado a 2% ao mês (95,02 mil).",
       "D": "Não confere com o saldo devedor capitalizado a 2% ao mês (95,02 mil).",
       "E": "Não confere com o saldo devedor capitalizado a 2% ao mês (95,02 mil)."},
      "Juros compostos: equivalência de capitais na data focal (conta refeita)"),

    q("contabeis", 47, GERAL_AUDITOR, "Contabilidade Avançada", "Equivalência patrimonial com lucro não realizado",
      "A empresa E1 S.A. detém 80% do capital social votante da empresa E2 S.A. e avalia esse investimento pelo método da equivalência patrimonial. Em 31 de dezembro de 2024, o Patrimônio Líquido de E2 totalizava R$ 1.000.000,00. Durante 2025, a empresa E2 obteve um lucro líquido de R$ 250.000,00, tendo vendido, durante o ano de 2025, mercadorias para E1 pelo valor de R$ 80.000,00, com margem de lucro de 30%. Dos estoques que E1 adquiriu de E2, somente 70% foram vendidos para terceiros.\n\nConsiderando-se todas as informações apresentadas, conclui-se que a receita de equivalência patrimonial de E1 S.A., em 2025, em reais, foi de",
      {"A": "180.800",
       "B": "194.240",
       "C": "195.392",
       "D": "244.240",
       "E": "250.000"},
      "B",
      "Lucro na venda de E2 para E1: 80.000 x 30% = 24.000. Ficou em estoque de E1 30% das mercadorias, então o lucro não realizado é 24.000 x 30% = 7.200. Equivalência = 80% x (250.000 - 7.200) = 194.240.",
      {"A": "Elimina todo o lucro intragrupo (24.000), inclusive a parte já vendida a terceiros, que está realizada: 80% x (250.000 - 24.000) = 180.800.",
       "B": "Correta. 80% x (250.000 - 7.200) = 194.240.",
       "C": "Elimina só 80% do lucro não realizado antes de aplicar a participação, aplicando o percentual duas vezes: 80% x (250.000 - 5.760) = 195.392.",
       "D": "Deduz a parcela do lucro não realizado, mas esquece de aplicar a participação de 80%: 250.000 - 5.760 = 244.240.",
       "E": "Reconhece o lucro inteiro de E2, sem aplicar a participação e sem eliminar o lucro não realizado."},
      "CPC 18 (R2) e ICPC 09 (R2): eliminação de lucros não realizados em operações entre investidora e investida"),

    q("contabeis", 54, GERAL_AMBOS, "Direito Tributário", "Natureza jurídica do tributo (CTN, art. 4º)",
      "Definido no Código Tributário Nacional como prestação pecuniária compulsória, em moeda ou cujo valor nela se possa exprimir, desde que não seja sanção por ato ilícito, o tributo possui subdivisões, dependendo de sua natureza jurídica específica.\n\nO tributo é determinado por",
      {"A": "imposto",
       "B": "fato gerador",
       "C": "vencimento",
       "D": "taxa",
       "E": "contribuição"},
      "B",
      "Pelo art. 4º do CTN, a natureza jurídica específica do tributo é determinada pelo fato gerador da respectiva obrigação, sendo irrelevantes a denominação e a destinação legal do produto da arrecadação.",
      {"A": "Imposto é uma das espécies tributárias (CTN, art. 5º), não o critério que define a natureza do tributo.",
       "B": "Correta. CTN, art. 4º: a natureza jurídica específica do tributo é determinada pelo fato gerador.",
       "C": "O vencimento é o prazo de pagamento; não define a natureza do tributo.",
       "D": "Taxa é espécie tributária, não critério de classificação.",
       "E": "Contribuição é espécie tributária, não critério de classificação."},
      "CTN (Lei nº 5.172/1966), arts. 3º, 4º e 5º"),

    q("contabeis", 58, GERAL_AUDITOR, "Contabilidade de Custos", "Margem de contribuição",
      "Um produto de uma empresa possui custo direto variável de R$ 1.000,00, custo indireto variável de R$ 1.500,00, custo fixo de R$ 2.000,00 e preço de venda de R$ 5.000,00.\n\nSendo assim, constata-se que o valor de margem de contribuição, em reais, é de",
      {"A": "500",
       "B": "2.500",
       "C": "3.000",
       "D": "3.500",
       "E": "4.000"},
      "B",
      "Margem de contribuição = preço de venda - custos e despesas variáveis (diretos e indiretos). MC = 5.000 - (1.000 + 1.500) = 2.500. O custo fixo não entra no cálculo.",
      {"A": "Subtrai também o custo fixo (5.000 - 4.500); isso é lucro, não margem de contribuição.",
       "B": "Correta. 5.000 - 1.000 - 1.500 = 2.500.",
       "C": "Subtrai apenas o custo fixo (5.000 - 2.000), invertendo o conceito.",
       "D": "Subtrai apenas o custo indireto variável (5.000 - 1.500).",
       "E": "Subtrai apenas o custo direto variável (5.000 - 1.000); o custo indireto variável também é variável e deve sair."},
      "Custeio variável: margem de contribuição = preço - custos e despesas variáveis"),

    q("contabeis", 62, GERAL_AUDITOR, "Contabilidade de Custos", "Ponto de equilíbrio contábil",
      "O ponto de equilíbrio contábil é um importante mecanismo para analisar a relação entre custo, despesa e receita. Considerando-se uma empresa que possui custos e despesas variáveis no valor de R$ 1.000,00 por unidade, custos e despesas fixas no valor de R$ 1.000.000,00 ao ano e preço de venda no valor de R$ 1.200,00 a unidade, o ponto de equilíbrio contábil corresponde ao valor, em vendas no ano, de",
      {"A": "R$ 833,33",
       "B": "R$ 1.000,00",
       "C": "R$ 5.000,00",
       "D": "R$ 1.200.000,00",
       "E": "R$ 6.000.000,00"},
      "E",
      "PE contábil em unidades = custos e despesas fixos / margem de contribuição unitária = 1.000.000 / (1.200 - 1.000) = 5.000 unidades. Em valor de vendas: 5.000 x 1.200 = R$ 6.000.000,00.",
      {"A": "Divide o custo fixo pelo preço (1.000.000 / 1.200) e ainda trata o resultado como valor monetário; não é a fórmula do ponto de equilíbrio.",
       "B": "Não corresponde à fórmula; 1.000 é o custo variável unitário.",
       "C": "5.000 é o ponto de equilíbrio em unidades, não o valor das vendas em reais.",
       "D": "Não decorre da fórmula do ponto de equilíbrio (o correto é 5.000 unidades x R$ 1.200).",
       "E": "Correta. 5.000 unidades x R$ 1.200 = R$ 6.000.000,00."},
      "Análise custo-volume-lucro: PE contábil = custos fixos / margem de contribuição unitária"),

    # ------------------------------------------------------------------ Prova 10: Direito
    q("direito", 44, GERAL_AMBOS, "Direito Tributário", "Imunidade recíproca de empresa pública prestadora de serviço público",
      "Após sucessivos embates judiciais, o Supremo Tribunal Federal decidiu que a Empresa Brasileira de Correios e Telégrafos (ECT) seria equiparada à União Federal, possuindo as mesmas prerrogativas. Com tal decisão, a ECT promoveu ações originárias para não pagamento do imposto sobre veículos automotores (IPVA) daqueles integrantes da sua frota.\n\nNos termos da Constituição Federal de 1988, tal alegação é fundamentada na",
      {"A": "não incidência",
       "B": "estruturação elisiva",
       "C": "isenção qualificada",
       "D": "imunidade recíproca",
       "E": "equiparação de impostos"},
      "D",
      "A CF/88 (art. 150, VI, a) veda que os entes instituam impostos sobre patrimônio, renda ou serviços uns dos outros. O STF estendeu essa imunidade recíproca à ECT, empresa pública prestadora de serviço público em regime de exclusividade, alcançando o IPVA de seus veículos.",
      {"A": "A propriedade de veículo automotor está dentro do campo de incidência do IPVA; o que afasta a cobrança é uma regra constitucional de imunidade.",
       "B": "Elisão é planejamento tributário lícito do contribuinte, sem relação com prerrogativa constitucional.",
       "C": "Isenção é dispensa concedida por lei do ente tributante; aqui a dispensa decorre diretamente da Constituição.",
       "D": "Correta. Imunidade recíproca (CF, art. 150, VI, a), estendida pelo STF à ECT.",
       "E": "\"Equiparação de impostos\" não é instituto do direito tributário."},
      "CF/88, art. 150, VI, a, e § 2º; jurisprudência do STF sobre a imunidade recíproca da ECT"),

    q("direito", 51, GERAL_AMBOS, "Direito Constitucional", "Competência privativa do Senado: operações externas",
      "A União Federal, com o intuito de prover recursos para projetos de infraestrutura, pretende obter empréstimo externo do Banco Mundial.\n\nNos termos da Constituição Federal de 1988, a autorização de operações externas de natureza financeira, de interesse da União, dos Estados, do Distrito Federal, dos Territórios e dos Municípios, compete privativamente ao",
      {"A": "Senado Federal",
       "B": "Congresso Nacional",
       "C": "Banco Central do Brasil",
       "D": "Conselho Monetário Nacional",
       "E": "Presidente da Câmara dos Deputados"},
      "A",
      "CF/88, art. 52, V: compete privativamente ao Senado Federal autorizar operações externas de natureza financeira de interesse da União, dos Estados, do Distrito Federal, dos Territórios e dos Municípios.",
      {"A": "Correta. CF/88, art. 52, V.",
       "B": "A competência é privativa do Senado, não do Congresso Nacional.",
       "C": "O Banco Central regula e fiscaliza o câmbio, mas não tem competência constitucional para autorizar essas operações.",
       "D": "O CMN formula a política monetária e de crédito, sem essa competência constitucional.",
       "E": "O Presidente da Câmara não tem essa atribuição."},
      "CF/88, art. 52, V"),

    q("direito", 52, GERAL_AMBOS, "Direito Constitucional", "Lei de Diretrizes Orçamentárias e agências de fomento",
      "Um engenheiro foi designado pelo banco de investimentos, onde ocupa o cargo de gerente, para acompanhar as discussões legislativas sobre a construção do orçamento federal pertinentes a verbas de investimento.\n\nNos termos da Constituição Federal de 1988, o estabelecimento da política de aplicação das agências financeiras oficiais de fomento deve constar da Lei de",
      {"A": "Gastos Anuais",
       "B": "Contabilidade Pública",
       "C": "Planejamento Tributário",
       "D": "Responsabilidade Fiscal",
       "E": "Diretrizes Orçamentárias"},
      "E",
      "CF/88, art. 165, § 2º: a lei de diretrizes orçamentárias estabelecerá a política de aplicação das agências financeiras oficiais de fomento, entre outros conteúdos.",
      {"A": "Não existe \"Lei de Gastos Anuais\"; a lei anual é a Lei Orçamentária Anual, que não é o instrumento indicado pela Constituição para esse conteúdo.",
       "B": "Não há \"Lei de Contabilidade Pública\" com essa função na Constituição.",
       "C": "Não existe \"Lei de Planejamento Tributário\" no sistema orçamentário.",
       "D": "A Lei de Responsabilidade Fiscal (LC 101/2000) trata de normas de gestão fiscal, mas a Constituição atribui esse conteúdo à LDO.",
       "E": "Correta. CF/88, art. 165, § 2º."},
      "CF/88, art. 165, § 2º"),

    q("direito", 58, GERAL_AMBOS, "Direito Tributário", "Anterioridade e majoração do Imposto de Renda",
      "Considere que determinada lei, promulgada no ano de 2020, majorou a alíquota do Imposto Sobre a Renda incidente sobre as exportações incentivadas para 20%.\n\nEssa lei será aplicada",
      {"A": "no ano de sua publicação, desde que ainda não tenha sido encerrado o exercício fiscal.",
       "B": "no exercício financeiro seguinte à sua publicação, respeitando-se os objetivos extrafiscais da tributação na espécie.",
       "C": "desde o ano base de 2019, visto que o fato gerador do imposto de renda é complexivo e se protrai no tempo.",
       "D": "em 2020, já que a lei tributária se aplica aos fatos geradores pendentes, cuja ocorrência tenha tido início, mas não tenha sido completada.",
       "E": "de imediato, visto que o ato autorizativo de benefícios fiscais não gera para o contribuinte direito adquirido qualquer, podendo ser revisto."},
      "B",
      "A majoração do IR se submete à irretroatividade e à anterioridade de exercício (CF, art. 150, III, a e b); o IR só está dispensado da noventena (art. 150, § 1º). O STF afastou a aplicação da lei ao próprio ano-base (cancelamento da Súmula 584) e, no caso das exportações incentivadas, reconheceu o caráter extrafiscal da tributação. A lei vale a partir do exercício seguinte.",
      {"A": "Aplicar a lei no mesmo exercício violaria a anterioridade anual, da qual o IR não está excepcionado.",
       "B": "Correta. Anterioridade de exercício e respeito à finalidade extrafiscal do incentivo às exportações.",
       "C": "Alcançar 2019 seria retroatividade vedada pelo art. 150, III, a, da Constituição.",
       "D": "A tese dos fatos geradores pendentes (CTN, art. 105) não autoriza aplicar ao próprio ano a majoração; o STF cancelou a Súmula 584, que admitia essa aplicação.",
       "E": "A aplicação imediata ignora a anterioridade de exercício, garantia constitucional do contribuinte."},
      "CF/88, art. 150, III, a e b, e § 1º; STF, cancelamento da Súmula 584 (2020)"),

    q("direito", 64, GERAL_AMBOS, "Direito Administrativo - Licitações", "Lei 14.133/2021: encargos do contratado",
      "O BNDES realizou com uma empresa um contrato de prestação de serviços cujo objeto é a manutenção do equipamento de informática. A empresa contratada sobrestou a execução do contrato sob alegação de que o recolhimento dos encargos oriundos da rescisão contratual de alguns de seus empregados a onerou demasiadamente, ensejando o desequilíbrio econômico-financeiro.\n\nNos termos da Lei nº 14.133/2021,",
      {"A": "o BNDES será responsável pelos encargos fiscais resultantes da execução do contrato.",
       "B": "o BNDES será responsável pelos encargos trabalhistas resultantes da execução do contrato.",
       "C": "o BNDES será responsável pelos encargos comerciais resultantes da execução do contrato.",
       "D": "o BNDES será responsável pelos encargos previdenciários resultantes da execução do contrato.",
       "E": "somente o contratado será responsável pelos encargos trabalhistas, previdenciários, fiscais e comerciais resultantes da execução do contrato."},
      "E",
      "Lei 14.133/2021, art. 121: somente o contratado responde pelos encargos trabalhistas, previdenciários, fiscais e comerciais da execução do contrato, e sua inadimplência não transfere a responsabilidade à Administração (§ 1º). A exceção do § 2º vale para serviços contínuos com dedicação exclusiva de mão de obra, o que não é o caso descrito.",
      {"A": "Os encargos fiscais são do contratado (art. 121, caput).",
       "B": "Os encargos trabalhistas são do contratado; a responsabilidade subsidiária da Administração (art. 121, § 2º) só existe em serviços com dedicação exclusiva de mão de obra e falha na fiscalização.",
       "C": "Os encargos comerciais são do contratado (art. 121, caput).",
       "D": "Os encargos previdenciários são do contratado; a solidariedade da Administração (art. 121, § 2º) também se limita aos contratos com dedicação exclusiva de mão de obra.",
       "E": "Correta. Lei 14.133/2021, art. 121, caput e § 1º."},
      "Lei nº 14.133/2021, art. 121"),
]


def validar(item):
    letras = sorted(item["options"])
    assert letras == ["A", "B", "C", "D", "E"], f"{item['id']}: alternativas {letras}"
    assert item["correct"] in item["options"], f"{item['id']}: gabarito fora das alternativas"
    assert sorted(item["option_explanations"]) == letras, f"{item['id']}: justificativas incompletas"
    assert item["option_explanations"][item["correct"]].startswith("Correta"), f"{item['id']}: justificativa do gabarito"
    for letra, texto in item["option_explanations"].items():
        if letra != item["correct"]:
            assert not texto.startswith("Correta"), f"{item['id']}: alternativa {letra} marcada como correta"


def main():
    with open(ARQ, encoding="utf-8") as f:
        banco = json.load(f)

    backup = os.path.join(BASE, f"questions.backup_{date.today():%Y%m%d}_antes_cesgranrio.json")
    if not os.path.exists(backup):
        shutil.copyfile(ARQ, backup)

    for item in QUESTOES:
        validar(item)
    ids = [item["id"] for item in QUESTOES]
    assert len(ids) == len(set(ids)), "ids repetidos no lote"

    restantes = [x for x in banco if not str(x.get("id", "")).startswith(PREFIXO)]
    banco_novo = restantes + QUESTOES
    with open(ARQ, "w", encoding="utf-8") as f:
        json.dump(banco_novo, f, ensure_ascii=False, indent=2)

    print(f"Lote Cesgranrio BNDES 2024: {len(QUESTOES)} questões (banco: {len(restantes)} -> {len(banco_novo)})")
    print(f"Backup: {os.path.basename(backup)}")


if __name__ == "__main__":
    main()
